export const FETCH_USER_POSTS_SUCCESS = 'FETCH_USER_POSTS_SUCCESS';
export const FETCH_USER_POSTS_FAIL = 'FETCH_USER_POSTS_FAIL';

export const FETCH_USER_POST_COMMENTS_SUCCESS = 'FETCH_USER_POST_COMMENTS_SUCCESS';
export const FETCH_USER_POST_COMMENTS_FAIL = 'FETCH_USER_POST_COMMENTS_FAIL';

export const ADD_POST_SUCCESS = 'ADD_POST_SUCCESS';
export const ADD_POST_FAIL = 'ADD_POST_FAIL';

export const DELETE_POST_SUCCESS = 'DELETE_POST_SUCCESS';
export const DELETE_POST_FAIL = 'DELETE_POST_FAIL';

export const EDIT_POST_SUCCESS = 'EDIT_POST_SUCCESS';
export const EDIT_POST_FAIL = 'EDIT_POST_FAIL';
